### ISSUE TITLE
cannot login

### ISSUE THREAD

**Issue by johnyzed** [mikeflynn/beats-app#1]
Hi, I have the following issue. I cannot connect from the username/password way. When I enter my credentials, it just stays in an infinite loop waiting ( with the circle thing ).
I tried to access beatsmusic from my regular browser  (chrome) and it worked.
I am working from a macbookpro with yosemite on it.

**Comment by mikeflynn** [comment]
Interesting. I do see any kind of loading of beatsmusic.com through the app is very slow at the moment. I can't inspect it, but wondering if Beats is starting to block the app. I'll keep investigating and keep this issue open in the meantime.

**Comment by mikeflynn** [comment]
I may have jumped the gun as this issue appears to be on the beatsmusic.com side. I'm unable to login from any browser on my computer in addition to the Chrome app.

**Comment by johnyzed** [comment]
it seems to be working now, thanks
